# on:
#   schedule:
#     - cron: "0 * * * *"  # Every hour

on: workflow_dispatch

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

name: Scrape Data
jobs:
  scrape-latest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master # check out the repo this action is in
      - name: Setup Python
        uses: actions/setup-python@v2.0.0
        with:
          python-version: "3.8"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Scrape
        env:
          DB_CONN_STRING: ${{ secrets.DB_CONN_STRING }}
        run: python -m scrapper.main
